//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.App.Model.SYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetPaytypeDto
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string PayType { get; set; }
        public string IsReturnT { get; set; }
        public string IsIntegralT { get; set; }
        public string IsDefaultT { get; set; }
        public bool IsReturn { get; set; }
        public bool IsIntegral { get; set; }
        public bool IsDefault { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool IsValid { get; set; }
        public string CreatedBy { get; set; }
    }
}
